export const characters = {
  firegirl: {
    id: "firegirl",
    name: "Fire Girl",
    x: 209,
    y: 456,
    direction: "up",
    stopped: true,
    takenBy: null,
  },
  archer: {
    id: "archer",
    name: "Archer",
    x: 183,
    y: 456,
    direction: "up",
    stopped: true,
    takenBy: null,
  },
  wizard: {
    id: "wizard",
    name: "Ice Wizard",
    x: 235,
    y: 456,
    direction: "up",
    stopped: true,
    takenBy: null,
  },
  ninja: {
    id: "ninja",
    name: "Ninja",
    x: 262,
    y: 456,
    direction: "up",
    stopped: true,
    takenBy: null,
  },
};
