export const characters = [
  {
    flipX: false,
    name: "Fire Girl",
    spritename: "fireGirl",
    x: 209,
    y: 456,
    direction: "up",
    stopped: true,
    idx: 0,
    takenBy: null,
    idlespriteidx: 1,
    leftFrames: [4, 3, 4, 5],
    rightFrames: [7, 6, 7, 8],
    upFrames: [10, 9, 10, 11],
    downFrames: [1, 0, 1, 2],
  },
  {
    flipX: false,
    name: "Boy",
    spritename: "player",
    x: 183,
    y: 456,
    direction: "up",
    stopped: true,
    idx: 1,
    takenBy: null,
    idlespriteidx: 0,
    leftFrames: [1, 7, 1, 13],
    rightFrames: [1, 7, 1, 13],
    upFrames: [2, 8, 2, 14],
    downFrames: [0, 6, 0, 12],
  },
  {
    flipX: false,
    name: "Ice Wizard",
    spritename: "wizard",
    x: 235,
    y: 456,
    direction: "up",
    stopped: true,
    idx: 2,
    takenBy: null,
    idlespriteidx: 1,
    leftFrames: [4, 3, 4, 5],
    rightFrames: [7, 6, 7, 8],
    upFrames: [10, 9, 10, 11],
    downFrames: [1, 0, 1, 2],
  },
  {
    flipX: false,
    name: "Snowman",
    spritename: "player",
    x: 262,
    y: 456,
    direction: "up",
    stopped: true,
    idx: 3,
    takenBy: null,
    idlespriteidx: 21,
    leftFrames: [22, 28, 22, 34],
    rightFrames: [22, 28, 22, 34],
    upFrames: [23, 29, 23, 35],
    downFrames: [21, 27, 21, 33],
  },
];
