export const enemies = {
  enemy1: {
    id: 1,
    name: "skeleton1",
    x: 210,
    y: 350,
    velx: 0,
    vely: 0,
    direction: "down",
    stopped: true,
    alive: true,
  },
  enemy2: {
    id: "2",
    name: "skeleton2",
    x: 230,
    y: 350,
    velx: 0,
    vely: 0,
    direction: "down",
    stopped: true,
    alive: true,
  },
  enemy3: {
    id: "3",
    name: "skeleton3",
    x: 250,
    y: 350,
    velx: 0,
    vely: 0,
    direction: "down",
    stopped: true,
    alive: true,
  },
};
